name: bokun_spize
description: 'Calorie tracking application in Flutter.'
publish_to: 'none'
version: 0.3.5+305

#
# DEPLOYING APP
# 1. `pubspec.yaml` -> Bump version number
# 2. `release_notes.txt` -> Update changelog for all languages
# 3. `default.txt` -> Update changelog for all languages
#

#
# Android
# `cd android/ && fastlane play_store_release`
#
# GitHub Releases
# `cd android/ && fastlane github_release`
#
# iOS
# `cd ios/ && fastlane app_store_release`
#

environment:
  sdk: 3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: 6.7.1
  diacritic: 0.1.6
  firebase_ai: 3.14.1
  firebase_auth: 6.5.6
  firebase_core: 4.12.1
  firebase_storage: 13.4.5
  fl_chart: 1.2.0
  flutter_animate: 4.5.2
  flutter_displaymode: 0.7.0
  flutter_swipe_action_cell: 3.1.9
  fuzzywuzzy: 1.2.0
  get_it: 9.2.1
  google_sign_in: 7.2.0
  image_picker: 1.2.3
  intl: 0.20.3
  scroll_datetime_picker: 0.2.2
  sign_in_with_apple: 8.1.0
  speech_to_text: 7.4.0
  string_similarity: 2.2.0
  uuid: 4.6.0
  watch_it: 2.4.2

  calendar_date_picker2:
    git:
      url: https://github.com/jokilic/calendar_date_picker2.git
      ref: feature/on-value-changed-dialog

  phosphor_flutter:
    git:
      url: https://github.com/phosphor-icons/flutter.git
      ref: 514f0a883571c4453dbd6ee3041d1dcba4fb8fc7

dev_dependencies:
  build_runner: 2.15.1
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.8

dependency_overrides:
  intl: 0.20.3

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/Epilogue/Epilogue-Thin.ttf
          weight: 100
        - asset: assets/Epilogue/Epilogue-ExtraLight.ttf
          weight: 200
        - asset: assets/Epilogue/Epilogue-Light.ttf
          weight: 300
        - asset: assets/Epilogue/Epilogue-Regular.ttf
          weight: 400
        - asset: assets/Epilogue/Epilogue-Medium.ttf
          weight: 500
        - asset: assets/Epilogue/Epilogue-SemiBold.ttf
          weight: 600
        - asset: assets/Epilogue/Epilogue-Bold.ttf
          weight: 700
        - asset: assets/Epilogue/Epilogue-ExtraBold.ttf
          weight: 800
        - asset: assets/Epilogue/Epilogue-Black.ttf
          weight: 900

    - family: PlusJakartaSans
      fonts:
        - asset: assets/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
          weight: 100
        - asset: assets/PlusJakartaSans/PlusJakartaSans-Light.ttf
          weight: 200
        - asset: assets/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
          weight: 900

# Run code generation - `flutter pub run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_launcher_icons:
  image_path_android: 'assets/icon.png'
  image_path_ios: 'assets/icon.png'
  android: true
  ios: true
  adaptive_icon_background: 'assets/background.png'
  adaptive_icon_foreground: 'assets/splash_icon.png'
  adaptive_icon_foreground_inset: 16
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#DADADA'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#DADADA'
    theme_color: '#DADADA'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash_dark.png'
  android_12:
    image: 'assets/splash_icon.png'
    color: '#DADADA'
    color_dark: '#1F1D2C'
