import 'dart:math';

import 'package:flutter/material.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

class BokunSpizeIcons {
  static const logo = 'assets/logo.webp';

  static IconData getRandomFoodIcon() => foodIcons[Random().nextInt(foodIcons.length)];

  static final foodIcons = [
    PhosphorIcons.bowlFood(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.fish(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.fishSimple(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.shrimp(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.hamburger(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.pizza(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.acorn(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.avocado(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.avocado(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.beerBottle(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.beerStein(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.bowlSteam(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.brandy(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.bread(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.carrot(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.champagne(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.cheers(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.cheese(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.cherries(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.coffee(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.coffeeBean(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.cookie(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.cookingPot(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.egg(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.eggCrack(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.forkKnife(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.iceCream(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.jar(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.jarLabel(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.knife(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.martini(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.onigiri(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.orange(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.orangeSlice(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.oven(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.pepper(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.pintGlass(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.popcorn(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.popsicle(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.teaBag(
      PhosphorIconsStyle.duotone,
    ),
    PhosphorIcons.wine(
      PhosphorIconsStyle.duotone,
    ),
  ];
}
