// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bokun_spize/models/food.dart';
import 'package:bokun_spize/models/hive_adapters.dart';
import 'package:bokun_spize/models/meal.dart';
import 'package:bokun_spize/models/nutrition.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MealAdapter());
    registerAdapter(NutritionAdapter());
    registerAdapter(FoodAdapter());
  }
}
