// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpqr36TfqwFTYHVL0FRPRR4YePKnoDX_U',
    appId: '1:178689254446:web:7d4e1c39511a9ce4edabbf',
    messagingSenderId: '178689254446',
    projectId: 'bokun-spize',
    authDomain: 'bokun-spize.firebaseapp.com',
    storageBucket: 'bokun-spize.firebasestorage.app',
    measurementId: 'G-RED4DJMPGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpStf8NHt8B1rOp9UI0SiKMLZfktlZFw',
    appId: '1:178689254446:android:c95263b04b1a8d27edabbf',
    messagingSenderId: '178689254446',
    projectId: 'bokun-spize',
    storageBucket: 'bokun-spize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09cY8OGLSm0RX8nRpiFIVQ_4DsR3n_GQ',
    appId: '1:178689254446:ios:483406a68793b017edabbf',
    messagingSenderId: '178689254446',
    projectId: 'bokun-spize',
    storageBucket: 'bokun-spize.firebasestorage.app',
    iosBundleId: 'com.josipkilic.bokunSpize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09cY8OGLSm0RX8nRpiFIVQ_4DsR3n_GQ',
    appId: '1:178689254446:ios:483406a68793b017edabbf',
    messagingSenderId: '178689254446',
    projectId: 'bokun-spize',
    storageBucket: 'bokun-spize.firebasestorage.app',
    iosBundleId: 'com.josipkilic.bokunSpize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpqr36TfqwFTYHVL0FRPRR4YePKnoDX_U',
    appId: '1:178689254446:web:0c36947f22efcac7edabbf',
    messagingSenderId: '178689254446',
    projectId: 'bokun-spize',
    authDomain: 'bokun-spize.firebaseapp.com',
    storageBucket: 'bokun-spize.firebasestorage.app',
    measurementId: 'G-5RJ29W7ECC',
  );
}
